# Generated by Django 5.2 on 2025-05-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuário'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
