services:
  db-api:
    image: postgres:16
    container_name: django-api-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdatabase_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: django-api-pgadmin
    depends_on:
      - db-api
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin123}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    container_name: redis
    hostname: redis
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT:-6379}
    ports:
      - "8081:8081"

volumes:
  pgdatabase_data:
  pgadmin_data:
  redis_data:
